---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.


12.2

Henry Tang:
Since repository was done, didn't need to do anything but clone

Caleb Moe:
Repo was set up for us, just cloned it.

Norah Wade: 
Repository was succesfully set up for us prior to lab.

12.3

Norah Wade: 
Succesfully cloned the repo via RStudio. 

Isabel Lange: 
Got the link from the repository

Caleb Moe:
No Problems cloning repo, hardest part was just figuring out the layout of RStudio

Henry Tang: No problems here.

Isabel Lange: Copied the repository link into RStudio.

12.4

Norah Wade: 

Completed succesfully. Ran into some merge conflicts. Resolved
through Git terminal because we were not familiar with RStudio handling Git conflicts.


Caleb Moe:
This is a line from RStudio

Norah Wade: This is a line from RStudio:)

Henry Tang:
This is a line from RStudio

Isabel Lange:
This is a line from RStudio

12.5

Henry Tang:
Pushed changes successfully

Isabel Lange: Followed steps to commit changes to repo

Norah Wade: Pushes were successful

Caleb Moe: 
Pushes were successful, no problems.

12.6

Caleb Moe:
Pushes appear in github repo.

Henry Tang:
Yes, the commits and pushes went through to the repo

Isabel Lange:
Changes are shown in github

Norah Wade: Confirmed through commit history.
